/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BanLicenseByKeyResponse model module.
 * @module model/BanLicenseByKeyResponse
 * @version 1.0.10
 */
class BanLicenseByKeyResponse {
    /**
     * Constructs a new <code>BanLicenseByKeyResponse</code>.
     * @alias module:model/BanLicenseByKeyResponse
     */
    constructor() { 
        
        BanLicenseByKeyResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BanLicenseByKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BanLicenseByKeyResponse} obj Optional instance to populate.
     * @return {module:model/BanLicenseByKeyResponse} The populated <code>BanLicenseByKeyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BanLicenseByKeyResponse();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
BanLicenseByKeyResponse.prototype['message'] = undefined;






export default BanLicenseByKeyResponse;

