/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckoutLog model module.
 * @module model/CheckoutLog
 * @version 1.0.10
 */
class CheckoutLog {
    /**
     * Constructs a new <code>CheckoutLog</code>.
     * @alias module:model/CheckoutLog
     */
    constructor() { 
        
        CheckoutLog.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CheckoutLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckoutLog} obj Optional instance to populate.
     * @return {module:model/CheckoutLog} The populated <code>CheckoutLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckoutLog();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('bot_id')) {
                obj['bot_id'] = ApiClient.convertToType(data['bot_id'], 'Number');
            }
            if (data.hasOwnProperty('seller_bot_id')) {
                obj['seller_bot_id'] = ApiClient.convertToType(data['seller_bot_id'], 'Number');
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('product_name')) {
                obj['product_name'] = ApiClient.convertToType(data['product_name'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
CheckoutLog.prototype['id'] = undefined;

/**
 * @member {Number} bot_id
 */
CheckoutLog.prototype['bot_id'] = undefined;

/**
 * @member {Number} seller_bot_id
 */
CheckoutLog.prototype['seller_bot_id'] = undefined;

/**
 * @member {Number} user_id
 */
CheckoutLog.prototype['user_id'] = undefined;

/**
 * @member {String} key
 */
CheckoutLog.prototype['key'] = undefined;

/**
 * @member {String} product_name
 */
CheckoutLog.prototype['product_name'] = undefined;

/**
 * @member {String} website
 */
CheckoutLog.prototype['website'] = undefined;

/**
 * @member {Number} size
 */
CheckoutLog.prototype['size'] = undefined;

/**
 * @member {String} image_url
 */
CheckoutLog.prototype['image_url'] = undefined;

/**
 * @member {Number} price
 */
CheckoutLog.prototype['price'] = undefined;

/**
 * @member {String} created_at
 */
CheckoutLog.prototype['created_at'] = undefined;

/**
 * @member {String} updated_at
 */
CheckoutLog.prototype['updated_at'] = undefined;

/**
 * @member {module:model/CheckoutLog.StatusEnum} status
 */
CheckoutLog.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CheckoutLog['StatusEnum'] = {

    /**
     * value: "success"
     * @const
     */
    "success": "success",

    /**
     * value: "denied"
     * @const
     */
    "denied": "denied"
};



export default CheckoutLog;

