/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConfirmProductResponse model module.
 * @module model/ConfirmProductResponse
 * @version 1.0.10
 */
class ConfirmProductResponse {
    /**
     * Constructs a new <code>ConfirmProductResponse</code>.
     * @alias module:model/ConfirmProductResponse
     */
    constructor() { 
        
        ConfirmProductResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConfirmProductResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConfirmProductResponse} obj Optional instance to populate.
     * @return {module:model/ConfirmProductResponse} The populated <code>ConfirmProductResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConfirmProductResponse();

            if (data.hasOwnProperty('confirmation')) {
                obj['confirmation'] = ApiClient.convertToType(data['confirmation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} confirmation
 */
ConfirmProductResponse.prototype['confirmation'] = undefined;






export default ConfirmProductResponse;

