/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Link from './Link';

/**
 * The CreateLinkResponse model module.
 * @module model/CreateLinkResponse
 * @version 1.0.10
 */
class CreateLinkResponse {
    /**
     * Constructs a new <code>CreateLinkResponse</code>.
     * @alias module:model/CreateLinkResponse
     */
    constructor() { 
        
        CreateLinkResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateLinkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateLinkResponse} obj Optional instance to populate.
     * @return {module:model/CreateLinkResponse} The populated <code>CreateLinkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateLinkResponse();

            if (data.hasOwnProperty('link')) {
                obj['link'] = Link.constructFromObject(data['link']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/Link} link
 */
CreateLinkResponse.prototype['link'] = undefined;






export default CreateLinkResponse;

