/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CheckoutLog from './CheckoutLog';

/**
 * The CreateCheckoutLogResponse model module.
 * @module model/CreateCheckoutLogResponse
 * @version 1.0.10
 */
class CreateCheckoutLogResponse {
    /**
     * Constructs a new <code>CreateCheckoutLogResponse</code>.
     * @alias module:model/CreateCheckoutLogResponse
     */
    constructor() { 
        
        CreateCheckoutLogResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateCheckoutLogResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCheckoutLogResponse} obj Optional instance to populate.
     * @return {module:model/CreateCheckoutLogResponse} The populated <code>CreateCheckoutLogResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCheckoutLogResponse();

            if (data.hasOwnProperty('checkout')) {
                obj['checkout'] = CheckoutLog.constructFromObject(data['checkout']);
            }
            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CheckoutLog} checkout
 */
CreateCheckoutLogResponse.prototype['checkout'] = undefined;

/**
 * @member {Boolean} success
 */
CreateCheckoutLogResponse.prototype['success'] = undefined;






export default CreateCheckoutLogResponse;

