/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateProductResponseProduct from './CreateProductResponseProduct';

/**
 * The CreateProductResponse model module.
 * @module model/CreateProductResponse
 * @version 1.0.10
 */
class CreateProductResponse {
    /**
     * Constructs a new <code>CreateProductResponse</code>.
     * @alias module:model/CreateProductResponse
     */
    constructor() { 
        
        CreateProductResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateProductResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateProductResponse} obj Optional instance to populate.
     * @return {module:model/CreateProductResponse} The populated <code>CreateProductResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateProductResponse();

            if (data.hasOwnProperty('success')) {
                obj['success'] = ApiClient.convertToType(data['success'], 'Boolean');
            }
            if (data.hasOwnProperty('formatted')) {
                obj['formatted'] = ApiClient.convertToType(data['formatted'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = CreateProductResponseProduct.constructFromObject(data['product']);
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} success
 */
CreateProductResponse.prototype['success'] = undefined;

/**
 * @member {String} formatted
 */
CreateProductResponse.prototype['formatted'] = undefined;

/**
 * @member {module:model/CreateProductResponseProduct} product
 */
CreateProductResponse.prototype['product'] = undefined;






export default CreateProductResponse;

