/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CheckoutLog from './CheckoutLog';

/**
 * The GetCheckoutLogsResponse model module.
 * @module model/GetCheckoutLogsResponse
 * @version 1.0.10
 */
class GetCheckoutLogsResponse {
    /**
     * Constructs a new <code>GetCheckoutLogsResponse</code>.
     * @alias module:model/GetCheckoutLogsResponse
     */
    constructor() { 
        
        GetCheckoutLogsResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCheckoutLogsResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCheckoutLogsResponse} obj Optional instance to populate.
     * @return {module:model/GetCheckoutLogsResponse} The populated <code>GetCheckoutLogsResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCheckoutLogsResponse();

            if (data.hasOwnProperty('checkouts')) {
                obj['checkouts'] = ApiClient.convertToType(data['checkouts'], [CheckoutLog]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/CheckoutLog>} checkouts
 */
GetCheckoutLogsResponse.prototype['checkouts'] = undefined;

/**
 * @member {Number} total
 */
GetCheckoutLogsResponse.prototype['total'] = undefined;






export default GetCheckoutLogsResponse;

