/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import License from './License';

/**
 * The GetLicensesResponse model module.
 * @module model/GetLicensesResponse
 * @version 1.0.10
 */
class GetLicensesResponse {
    /**
     * Constructs a new <code>GetLicensesResponse</code>.
     * @alias module:model/GetLicensesResponse
     */
    constructor() { 
        
        GetLicensesResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetLicensesResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetLicensesResponse} obj Optional instance to populate.
     * @return {module:model/GetLicensesResponse} The populated <code>GetLicensesResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetLicensesResponse();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [License]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/License>} users
 */
GetLicensesResponse.prototype['users'] = undefined;






export default GetLicensesResponse;

