/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Link from './Link';

/**
 * The GetLinksResponse model module.
 * @module model/GetLinksResponse
 * @version 1.0.10
 */
class GetLinksResponse {
    /**
     * Constructs a new <code>GetLinksResponse</code>.
     * @alias module:model/GetLinksResponse
     */
    constructor() { 
        
        GetLinksResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetLinksResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetLinksResponse} obj Optional instance to populate.
     * @return {module:model/GetLinksResponse} The populated <code>GetLinksResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetLinksResponse();

            if (data.hasOwnProperty('links')) {
                obj['links'] = ApiClient.convertToType(data['links'], [Link]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/Link>} links
 */
GetLinksResponse.prototype['links'] = undefined;






export default GetLinksResponse;

