/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import License from './License';
import LicenseDiscord from './LicenseDiscord';
import LicensePlan from './LicensePlan';
import LicenseTwitter from './LicenseTwitter';
import Metadata from './Metadata';

/**
 * The GetLicenseByKeyResponse model module.
 * @module model/GetLicenseByKeyResponse
 * @version 1.0.10
 */
class GetLicenseByKeyResponse {
    /**
     * Constructs a new <code>GetLicenseByKeyResponse</code>.
     * @alias module:model/GetLicenseByKeyResponse
     * @implements module:model/License
     */
    constructor() { 
        License.initialize(this);
        GetLicenseByKeyResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetLicenseByKeyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetLicenseByKeyResponse} obj Optional instance to populate.
     * @return {module:model/GetLicenseByKeyResponse} The populated <code>GetLicenseByKeyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetLicenseByKeyResponse();
            License.constructFromObject(data, obj);

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('rental_key')) {
                obj['rental_key'] = ApiClient.convertToType(data['rental_key'], 'String');
            }
            if (data.hasOwnProperty('rented')) {
                obj['rented'] = ApiClient.convertToType(data['rented'], 'Boolean');
            }
            if (data.hasOwnProperty('rental_end')) {
                obj['rental_end'] = ApiClient.convertToType(data['rental_end'], 'String');
            }
            if (data.hasOwnProperty('valid')) {
                obj['valid'] = ApiClient.convertToType(data['valid'], 'Boolean');
            }
            if (data.hasOwnProperty('key_status')) {
                obj['key_status'] = ApiClient.convertToType(data['key_status'], 'String');
            }
            if (data.hasOwnProperty('subscription_status')) {
                obj['subscription_status'] = ApiClient.convertToType(data['subscription_status'], 'String');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
            if (data.hasOwnProperty('banned')) {
                obj['banned'] = ApiClient.convertToType(data['banned'], 'Boolean');
            }
            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = Metadata.constructFromObject(data['metadata']);
            }
            if (data.hasOwnProperty('next_renewal_date')) {
                obj['next_renewal_date'] = ApiClient.convertToType(data['next_renewal_date'], 'String');
            }
            if (data.hasOwnProperty('renewal_period')) {
                obj['renewal_period'] = ApiClient.convertToType(data['renewal_period'], 'Number');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
            }
            if (data.hasOwnProperty('discord')) {
                obj['discord'] = LicenseDiscord.constructFromObject(data['discord']);
            }
            if (data.hasOwnProperty('twitter')) {
                obj['twitter'] = LicenseTwitter.constructFromObject(data['twitter']);
            }
            if (data.hasOwnProperty('is_scammer')) {
                obj['is_scammer'] = ApiClient.convertToType(data['is_scammer'], Object);
            }
            if (data.hasOwnProperty('plan')) {
                obj['plan'] = LicensePlan.constructFromObject(data['plan']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
GetLicenseByKeyResponse.prototype['id'] = undefined;

/**
 * @member {String} key
 */
GetLicenseByKeyResponse.prototype['key'] = undefined;

/**
 * @member {String} rental_key
 */
GetLicenseByKeyResponse.prototype['rental_key'] = undefined;

/**
 * @member {Boolean} rented
 */
GetLicenseByKeyResponse.prototype['rented'] = undefined;

/**
 * @member {String} rental_end
 */
GetLicenseByKeyResponse.prototype['rental_end'] = undefined;

/**
 * @member {Boolean} valid
 */
GetLicenseByKeyResponse.prototype['valid'] = undefined;

/**
 * @member {module:model/GetLicenseByKeyResponse.KeyStatusEnum} key_status
 */
GetLicenseByKeyResponse.prototype['key_status'] = undefined;

/**
 * @member {module:model/GetLicenseByKeyResponse.SubscriptionStatusEnum} subscription_status
 */
GetLicenseByKeyResponse.prototype['subscription_status'] = undefined;

/**
 * @member {Number} quantity
 */
GetLicenseByKeyResponse.prototype['quantity'] = undefined;

/**
 * @member {Boolean} banned
 */
GetLicenseByKeyResponse.prototype['banned'] = undefined;

/**
 * @member {module:model/Metadata} metadata
 */
GetLicenseByKeyResponse.prototype['metadata'] = undefined;

/**
 * @member {String} next_renewal_date
 */
GetLicenseByKeyResponse.prototype['next_renewal_date'] = undefined;

/**
 * @member {Number} renewal_period
 */
GetLicenseByKeyResponse.prototype['renewal_period'] = undefined;

/**
 * @member {String} created_at
 */
GetLicenseByKeyResponse.prototype['created_at'] = undefined;

/**
 * @member {module:model/LicenseDiscord} discord
 */
GetLicenseByKeyResponse.prototype['discord'] = undefined;

/**
 * @member {module:model/LicenseTwitter} twitter
 */
GetLicenseByKeyResponse.prototype['twitter'] = undefined;

/**
 * @member {Object} is_scammer
 */
GetLicenseByKeyResponse.prototype['is_scammer'] = undefined;

/**
 * @member {module:model/LicensePlan} plan
 */
GetLicenseByKeyResponse.prototype['plan'] = undefined;


// Implement License interface:
/**
 * @member {Number} id
 */
License.prototype['id'] = undefined;
/**
 * @member {String} key
 */
License.prototype['key'] = undefined;
/**
 * @member {String} rental_key
 */
License.prototype['rental_key'] = undefined;
/**
 * @member {Boolean} rented
 */
License.prototype['rented'] = undefined;
/**
 * @member {String} rental_end
 */
License.prototype['rental_end'] = undefined;
/**
 * @member {Boolean} valid
 */
License.prototype['valid'] = undefined;
/**
 * @member {module:model/License.KeyStatusEnum} key_status
 */
License.prototype['key_status'] = undefined;
/**
 * @member {module:model/License.SubscriptionStatusEnum} subscription_status
 */
License.prototype['subscription_status'] = undefined;
/**
 * @member {Number} quantity
 */
License.prototype['quantity'] = undefined;
/**
 * @member {Boolean} banned
 */
License.prototype['banned'] = undefined;
/**
 * @member {module:model/Metadata} metadata
 */
License.prototype['metadata'] = undefined;
/**
 * @member {String} next_renewal_date
 */
License.prototype['next_renewal_date'] = undefined;
/**
 * @member {Number} renewal_period
 */
License.prototype['renewal_period'] = undefined;
/**
 * @member {String} created_at
 */
License.prototype['created_at'] = undefined;
/**
 * @member {module:model/LicenseDiscord} discord
 */
License.prototype['discord'] = undefined;
/**
 * @member {module:model/LicenseTwitter} twitter
 */
License.prototype['twitter'] = undefined;
/**
 * @member {Object} is_scammer
 */
License.prototype['is_scammer'] = undefined;
/**
 * @member {module:model/LicensePlan} plan
 */
License.prototype['plan'] = undefined;



/**
 * Allowed values for the <code>key_status</code> property.
 * @enum {String}
 * @readonly
 */
GetLicenseByKeyResponse['KeyStatusEnum'] = {

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",

    /**
     * value: "approved"
     * @const
     */
    "approved": "approved",

    /**
     * value: "listed"
     * @const
     */
    "listed": "listed",

    /**
     * value: "removed"
     * @const
     */
    "removed": "removed",

    /**
     * value: "sold"
     * @const
     */
    "sold": "sold",

    /**
     * value: "terminated"
     * @const
     */
    "terminated": "terminated",

    /**
     * value: "expired"
     * @const
     */
    "expired": "expired",

    /**
     * value: "disabled"
     * @const
     */
    "disabled": "disabled"
};


/**
 * Allowed values for the <code>subscription_status</code> property.
 * @enum {String}
 * @readonly
 */
GetLicenseByKeyResponse['SubscriptionStatusEnum'] = {

    /**
     * value: "completed"
     * @const
     */
    "completed": "completed",

    /**
     * value: "active"
     * @const
     */
    "active": "active",

    /**
     * value: "trialing"
     * @const
     */
    "trialing": "trialing",

    /**
     * value: "canceled"
     * @const
     */
    "canceled": "canceled"
};



export default GetLicenseByKeyResponse;

