/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LicenseDiscord model module.
 * @module model/LicenseDiscord
 * @version 1.0.10
 */
class LicenseDiscord {
    /**
     * Constructs a new <code>LicenseDiscord</code>.
     * @alias module:model/LicenseDiscord
     */
    constructor() { 
        
        LicenseDiscord.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LicenseDiscord</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LicenseDiscord} obj Optional instance to populate.
     * @return {module:model/LicenseDiscord} The populated <code>LicenseDiscord</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LicenseDiscord();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('discord_account_id')) {
                obj['discord_account_id'] = ApiClient.convertToType(data['discord_account_id'], 'String');
            }
            if (data.hasOwnProperty('image_url')) {
                obj['image_url'] = ApiClient.convertToType(data['image_url'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
LicenseDiscord.prototype['username'] = undefined;

/**
 * @member {String} discord_account_id
 */
LicenseDiscord.prototype['discord_account_id'] = undefined;

/**
 * @member {String} image_url
 */
LicenseDiscord.prototype['image_url'] = undefined;






export default LicenseDiscord;

