/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LicensePlan model module.
 * @module model/LicensePlan
 * @version 1.0.10
 */
class LicensePlan {
    /**
     * Constructs a new <code>LicensePlan</code>.
     * @alias module:model/LicensePlan
     */
    constructor() { 
        
        LicensePlan.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LicensePlan</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LicensePlan} obj Optional instance to populate.
     * @return {module:model/LicensePlan} The populated <code>LicensePlan</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LicensePlan();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('initial_price')) {
                obj['initial_price'] = ApiClient.convertToType(data['initial_price'], 'Number');
            }
            if (data.hasOwnProperty('renewal_price')) {
                obj['renewal_price'] = ApiClient.convertToType(data['renewal_price'], 'Number');
            }
            if (data.hasOwnProperty('billing_period')) {
                obj['billing_period'] = ApiClient.convertToType(data['billing_period'], 'Number');
            }
            if (data.hasOwnProperty('license_type')) {
                obj['license_type'] = ApiClient.convertToType(data['license_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
LicensePlan.prototype['id'] = undefined;

/**
 * @member {String} title
 */
LicensePlan.prototype['title'] = undefined;

/**
 * @member {Number} initial_price
 */
LicensePlan.prototype['initial_price'] = undefined;

/**
 * @member {Number} renewal_price
 */
LicensePlan.prototype['renewal_price'] = undefined;

/**
 * @member {Number} billing_period
 */
LicensePlan.prototype['billing_period'] = undefined;

/**
 * @member {module:model/LicensePlan.LicenseTypeEnum} license_type
 */
LicensePlan.prototype['license_type'] = undefined;





/**
 * Allowed values for the <code>license_type</code> property.
 * @enum {String}
 * @readonly
 */
LicensePlan['LicenseTypeEnum'] = {

    /**
     * value: "one_time"
     * @const
     */
    "one_time": "one_time",

    /**
     * value: "renewal"
     * @const
     */
    "renewal": "renewal"
};



export default LicensePlan;

