/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendPushNotificationRequest model module.
 * @module model/SendPushNotificationRequest
 * @version 1.0.10
 */
class SendPushNotificationRequest {
    /**
     * Constructs a new <code>SendPushNotificationRequest</code>.
     * @alias module:model/SendPushNotificationRequest
     */
    constructor() { 
        
        SendPushNotificationRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendPushNotificationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendPushNotificationRequest} obj Optional instance to populate.
     * @return {module:model/SendPushNotificationRequest} The populated <code>SendPushNotificationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendPushNotificationRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('link')) {
                obj['link'] = ApiClient.convertToType(data['link'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = ApiClient.convertToType(data['body'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The title to be displayed on the push notification.
 * @member {String} title
 */
SendPushNotificationRequest.prototype['title'] = undefined;

/**
 * The link to be displayed on the push notification.
 * @member {String} link
 */
SendPushNotificationRequest.prototype['link'] = undefined;

/**
 * The body text to display on the push notification.
 * @member {String} body
 */
SendPushNotificationRequest.prototype['body'] = undefined;






export default SendPushNotificationRequest;

