/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateLicenseByKeyRequest model module.
 * @module model/UpdateLicenseByKeyRequest
 * @version 1.0.10
 */
class UpdateLicenseByKeyRequest {
    /**
     * Constructs a new <code>UpdateLicenseByKeyRequest</code>.
     * @alias module:model/UpdateLicenseByKeyRequest
     */
    constructor() { 
        
        UpdateLicenseByKeyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateLicenseByKeyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateLicenseByKeyRequest} obj Optional instance to populate.
     * @return {module:model/UpdateLicenseByKeyRequest} The populated <code>UpdateLicenseByKeyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateLicenseByKeyRequest();

            if (data.hasOwnProperty('metadata')) {
                obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} metadata
 */
UpdateLicenseByKeyRequest.prototype['metadata'] = undefined;






export default UpdateLicenseByKeyRequest;

