/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import SendPushNotificationRequest from '../model/SendPushNotificationRequest';
import SendPushNotificationResponse from '../model/SendPushNotificationResponse';

/**
* Notifications service.
* @module api/NotificationsApi
* @version 1.0.10
*/
export default class NotificationsApi {

    /**
    * Constructs a new NotificationsApi. 
    * @alias module:api/NotificationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Send a push notification
     * @param {Object} opts Optional parameters
     * @param {module:model/SendPushNotificationRequest} opts.sendPushNotificationRequest Click the arrow to the right to see the full body.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SendPushNotificationResponse} and HTTP response
     */
    sendPushNotificationWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['sendPushNotificationRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SendPushNotificationResponse;
      return this.apiClient.callApi(
        '/v1/send_push_notification', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Send a push notification
     * @param {Object} opts Optional parameters
     * @param {module:model/SendPushNotificationRequest} opts.sendPushNotificationRequest Click the arrow to the right to see the full body.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SendPushNotificationResponse}
     */
    sendPushNotification(opts) {
      return this.sendPushNotificationWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
