/**
 * Whop API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.10
 * Contact: support@whop.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import Whop from './whop';
import ApiClient from './ApiClient';
import BanLicenseByKeyRequest from './model/BanLicenseByKeyRequest';
import BanLicenseByKeyResponse from './model/BanLicenseByKeyResponse';
import CheckoutLog from './model/CheckoutLog';
import ConfirmProductRequest from './model/ConfirmProductRequest';
import ConfirmProductResponse from './model/ConfirmProductResponse';
import CreateCheckoutLogRequest from './model/CreateCheckoutLogRequest';
import CreateCheckoutLogResponse from './model/CreateCheckoutLogResponse';
import CreateLinkRequest from './model/CreateLinkRequest';
import CreateLinkResponse from './model/CreateLinkResponse';
import CreateProductRequest from './model/CreateProductRequest';
import CreateProductResponse from './model/CreateProductResponse';
import CreateProductResponseProduct from './model/CreateProductResponseProduct';
import ErrorResponse from './model/ErrorResponse';
import GetCheckoutLogsResponse from './model/GetCheckoutLogsResponse';
import GetLicenseByKeyResponse from './model/GetLicenseByKeyResponse';
import GetLicensesResponse from './model/GetLicensesResponse';
import GetLinksResponse from './model/GetLinksResponse';
import GetProductByIdResponse from './model/GetProductByIdResponse';
import GetProductsResponse from './model/GetProductsResponse';
import License from './model/License';
import LicenseDiscord from './model/LicenseDiscord';
import LicensePlan from './model/LicensePlan';
import LicenseTwitter from './model/LicenseTwitter';
import Link from './model/Link';
import Metadata from './model/Metadata';
import Product from './model/Product';
import ResetLicenseByKeyRequest from './model/ResetLicenseByKeyRequest';
import ResetLicenseByKeyResponse from './model/ResetLicenseByKeyResponse';
import SendPushNotificationRequest from './model/SendPushNotificationRequest';
import SendPushNotificationResponse from './model/SendPushNotificationResponse';
import UpdateLicenseByKeyRequest from './model/UpdateLicenseByKeyRequest';
import UpdateLicenseByKeyRequestMetadata from './model/UpdateLicenseByKeyRequestMetadata';
import UpdateLicenseByKeyResponse from './model/UpdateLicenseByKeyResponse';
import ValidateLicenseByKeyRequest from './model/ValidateLicenseByKeyRequest';
import ValidateLicenseByKeyResponse from './model/ValidateLicenseByKeyResponse';
import CheckoutLogsApi from './api/CheckoutLogsApi';
import LicensesApi from './api/LicensesApi';
import LinksApi from './api/LinksApi';
import NotificationsApi from './api/NotificationsApi';
import ProductsApi from './api/ProductsApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var WhopApi = require('index'); // See note below*.
* var xxxSvc = new WhopApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new WhopApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new WhopApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new WhopApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.10
*/
export {
    /**
     * The Whop constuctor.
     * @property {module:whop}
     */
    Whop,
    
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The BanLicenseByKeyRequest model constructor.
     * @property {module:model/BanLicenseByKeyRequest}
     */
    BanLicenseByKeyRequest,

    /**
     * The BanLicenseByKeyResponse model constructor.
     * @property {module:model/BanLicenseByKeyResponse}
     */
    BanLicenseByKeyResponse,

    /**
     * The CheckoutLog model constructor.
     * @property {module:model/CheckoutLog}
     */
    CheckoutLog,

    /**
     * The ConfirmProductRequest model constructor.
     * @property {module:model/ConfirmProductRequest}
     */
    ConfirmProductRequest,

    /**
     * The ConfirmProductResponse model constructor.
     * @property {module:model/ConfirmProductResponse}
     */
    ConfirmProductResponse,

    /**
     * The CreateCheckoutLogRequest model constructor.
     * @property {module:model/CreateCheckoutLogRequest}
     */
    CreateCheckoutLogRequest,

    /**
     * The CreateCheckoutLogResponse model constructor.
     * @property {module:model/CreateCheckoutLogResponse}
     */
    CreateCheckoutLogResponse,

    /**
     * The CreateLinkRequest model constructor.
     * @property {module:model/CreateLinkRequest}
     */
    CreateLinkRequest,

    /**
     * The CreateLinkResponse model constructor.
     * @property {module:model/CreateLinkResponse}
     */
    CreateLinkResponse,

    /**
     * The CreateProductRequest model constructor.
     * @property {module:model/CreateProductRequest}
     */
    CreateProductRequest,

    /**
     * The CreateProductResponse model constructor.
     * @property {module:model/CreateProductResponse}
     */
    CreateProductResponse,

    /**
     * The CreateProductResponseProduct model constructor.
     * @property {module:model/CreateProductResponseProduct}
     */
    CreateProductResponseProduct,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The GetCheckoutLogsResponse model constructor.
     * @property {module:model/GetCheckoutLogsResponse}
     */
    GetCheckoutLogsResponse,

    /**
     * The GetLicenseByKeyResponse model constructor.
     * @property {module:model/GetLicenseByKeyResponse}
     */
    GetLicenseByKeyResponse,

    /**
     * The GetLicensesResponse model constructor.
     * @property {module:model/GetLicensesResponse}
     */
    GetLicensesResponse,

    /**
     * The GetLinksResponse model constructor.
     * @property {module:model/GetLinksResponse}
     */
    GetLinksResponse,

    /**
     * The GetProductByIdResponse model constructor.
     * @property {module:model/GetProductByIdResponse}
     */
    GetProductByIdResponse,

    /**
     * The GetProductsResponse model constructor.
     * @property {module:model/GetProductsResponse}
     */
    GetProductsResponse,

    /**
     * The License model constructor.
     * @property {module:model/License}
     */
    License,

    /**
     * The LicenseDiscord model constructor.
     * @property {module:model/LicenseDiscord}
     */
    LicenseDiscord,

    /**
     * The LicensePlan model constructor.
     * @property {module:model/LicensePlan}
     */
    LicensePlan,

    /**
     * The LicenseTwitter model constructor.
     * @property {module:model/LicenseTwitter}
     */
    LicenseTwitter,

    /**
     * The Link model constructor.
     * @property {module:model/Link}
     */
    Link,

    /**
     * The Metadata model constructor.
     * @property {module:model/Metadata}
     */
    Metadata,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ResetLicenseByKeyRequest model constructor.
     * @property {module:model/ResetLicenseByKeyRequest}
     */
    ResetLicenseByKeyRequest,

    /**
     * The ResetLicenseByKeyResponse model constructor.
     * @property {module:model/ResetLicenseByKeyResponse}
     */
    ResetLicenseByKeyResponse,

    /**
     * The SendPushNotificationRequest model constructor.
     * @property {module:model/SendPushNotificationRequest}
     */
    SendPushNotificationRequest,

    /**
     * The SendPushNotificationResponse model constructor.
     * @property {module:model/SendPushNotificationResponse}
     */
    SendPushNotificationResponse,

    /**
     * The UpdateLicenseByKeyRequest model constructor.
     * @property {module:model/UpdateLicenseByKeyRequest}
     */
    UpdateLicenseByKeyRequest,

    /**
     * The UpdateLicenseByKeyRequestMetadata model constructor.
     * @property {module:model/UpdateLicenseByKeyRequestMetadata}
     */
    UpdateLicenseByKeyRequestMetadata,

    /**
     * The UpdateLicenseByKeyResponse model constructor.
     * @property {module:model/UpdateLicenseByKeyResponse}
     */
    UpdateLicenseByKeyResponse,

    /**
     * The ValidateLicenseByKeyRequest model constructor.
     * @property {module:model/ValidateLicenseByKeyRequest}
     */
    ValidateLicenseByKeyRequest,

    /**
     * The ValidateLicenseByKeyResponse model constructor.
     * @property {module:model/ValidateLicenseByKeyResponse}
     */
    ValidateLicenseByKeyResponse,

    /**
    * The CheckoutLogsApi service constructor.
    * @property {module:api/CheckoutLogsApi}
    */
    CheckoutLogsApi,

    /**
    * The LicensesApi service constructor.
    * @property {module:api/LicensesApi}
    */
    LicensesApi,

    /**
    * The LinksApi service constructor.
    * @property {module:api/LinksApi}
    */
    LinksApi,

    /**
    * The NotificationsApi service constructor.
    * @property {module:api/NotificationsApi}
    */
    NotificationsApi,

    /**
    * The ProductsApi service constructor.
    * @property {module:api/ProductsApi}
    */
    ProductsApi
};
